### ISSUE TITLE
Insufficient testing

### ISSUE THREAD

**Issue by da440dil** [xorcare/incrementor#1]
What about yet another test?

```go
func TestIncrement(t *testing.T) {
	tests := []struct {
		Max int
		Res int
	}{
		{10, 9},
		{5, 4},
	}
	n := 1000

	for _, v := range tests {
		t.Run(fmt.Sprintf("%d/%d", v.Max, v.Res), func(t *testing.T) {
			increment := New()
			increment.SetMaximumValue(v.Max)
			for i := 1; i < n; i++ {
				increment.IncrementNumber()
			}
			if i := increment.GetNumber(); i != v.Res {
				t.Fatalf("incrementor: an incorrect counter value(%d/%d):%d", v.Max, v.Res, i)
			}
		})

		t.Run(fmt.Sprintf("%d/%d:parallel", v.Max, v.Res), func(t *testing.T) {
			increment := New()
			increment.SetMaximumValue(v.Max)
			var wg sync.WaitGroup
			for i := 1; i < n; i++ {
				wg.Add(1)
				go func() {
					increment.IncrementNumber()
					wg.Done()
				}()
			}
			wg.Wait()
			if i := increment.GetNumber(); i != v.Res {
				t.Fatalf("incrementor: an incorrect counter value(%d/%d):%d", v.Max, v.Res, i)
			}
		})
	}
}
```

Isn't it what you expected from Incrementor?

**Comment by xorcare** [comment]
Maybe you should, you just suggest or want to use this package?

**Comment by da440dil** [comment]
Все проще. 

На прошлой неделе hr скинул мне текст readme этого репозитория в качестве тестового задания. 
Я сделал по-быстрому простое (насколько это возможно, в моем понимании) решение и залил gist (уже удалил).
Позже я нашел этот репозиторий и понял что... если это "правильное" решение, то я что-то не понимаю. 

Сегодня решил поинтересоваться результатом и получил негативный отзыв (в котором в числе прочего было и про многопоточность, и, дословно: "В тесте достаточно сделать один инкремент, это читается проще. 10 итераций не проверяют что-то дополнительное. Почему не 15 или не 101?"). 

Хотелось бы знать, для общего развития, это и есть "эталонное" решение? И если да то причем здесь sync/atomic?

**Comment by xorcare** [comment]
Это брошеный на пол пути вечерний эсперимент.

**Comment by xorcare** [comment]
Я не автор данного задания наверно один из тех кто его делал на коленке и не для собеседовани, а уже после просто для практики.

- в тест кейсах нужно указывать название  что-бы как то отразить его суть

**Comment by xorcare** [comment]
Конкурентность можно реализовать через sync.Mutex (более удобный но патерн, но может быть менен производителен чем каналы) или каналы (канал это более популярный паттерн для конкурентности в go)

**Comment by da440dil** [comment]
Спасибо. Прошу прощения если что не так, предположил что Вы могли бы быть автором задания. 
На мой взгляд по readme трудно понять что имел ввиду автор, более того, когда я увидел Вашу реализацию это не особо добавило понимания.

Мое решение (без документации) выглядело примерно так:
```go
const maxInt = int(^uint(0) >> 1)

type Incrementor struct {
	value       int
	maxValue    int
	hasMaxValue bool
}

func (i *Incrementor) GetNumber() int {
	return i.value
}

func (i *Incrementor) IncrementNumber() {
	if i.hasMaxValue {
		if i.maxValue == 0 {
			return
		}
		i.increment(i.maxValue)
	} else {
		i.increment(maxInt)
	}
}

func (i *Incrementor) increment(maxValue int) {
	i.value += 1
	if i.value == maxValue {
		i.value = 0
	}
}

func (i *Incrementor) SetMaximumValue(maxValue int) {
	if maxValue < 0 {
		maxValue = 0
	}

	i.maxValue = maxValue
	i.hasMaxValue = true

	if i.value >= i.maxValue {
		i.value = 0
	}
}
```
Со всеми комментами, тестами (с названиями, отражающими суть), примерами, все билдилось в понятную (на мой взгляд) документацию (godoc).
Конкурентность оставлена юзеру, я намеренно не стал использовать sync.mutex, для простоты (о чем написал в документации, да и в readme об этом ни слова, как и о том что необходимо паниковать если юзер пытается установить maxValue меньше нуля), если нужно - втыкаем sync.mutex и тест, который я предложил выше, проходит. 
Разумеется я понимал что конструктор может упростить реализацию, но не реализовал его в пользу простоты использования. 

В общем если кто-то решит еще раз использовать текст readme этого репозитория в качестве тестового задания, рекомендую его уточнить (например "Если при смене максимального значения число резко начинает превышать..." оказывается "Если при смене максимального значения число больше или равно..."), да и реализацию тоже не мешало бы исправить.

Вопрос закрыт, удачи.
